name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Force XCode 11.3
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: Build
      run: xcodebuild -scheme WeatheryApp -destination platform=iOS\ Simulator,OS=13.3,name=iPhone\ 11 \ clean test | xcpretty
      
      
      
#     - name: Test
#       run: cd WeatheryAppTests; swift test --parallel; cd ..
